// <auto-generated />
using System;
using EnrollmentManagementAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace COMP306402_ProjectDemo.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251117223411_InitialLocalDBCreate")]
    partial class InitialLocalDBCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("COMP306402_ProjectDemo.Models.AcademicProgram", b =>
                {
                    b.Property<int>("ProgramId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProgramId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DurationMonths")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("TuitionFee")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ProgramId");

                    b.ToTable("AcedemicPrograms");

                    b.HasData(
                        new
                        {
                            ProgramId = 1,
                            Description = "Comprehensive software development curriculum.",
                            DurationMonths = 12,
                            Name = "Software Engineering",
                            TuitionFee = 15000.00m
                        },
                        new
                        {
                            ProgramId = 2,
                            Description = "Focus on network infrastructure and security.",
                            DurationMonths = 8,
                            Name = "Computer Networking",
                            TuitionFee = 12000.00m
                        },
                        new
                        {
                            ProgramId = 3,
                            Description = "Creative and technical skills for digital media.",
                            DurationMonths = 6,
                            Name = "Graphic Design Fundamentals",
                            TuitionFee = 8500.00m
                        });
                });

            modelBuilder.Entity("COMP306402_ProjectDemo.Models.Enrollment", b =>
                {
                    b.Property<int>("EnrollmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EnrollmentId"));

                    b.Property<DateTime>("EnrollmentDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProgramId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("EnrollmentId");

                    b.HasIndex("ProgramId");

                    b.HasIndex("StudentId");

                    b.ToTable("Enrollments");

                    b.HasData(
                        new
                        {
                            EnrollmentId = 1,
                            EnrollmentDate = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProgramId = 1,
                            Status = "Active",
                            StudentId = 1
                        },
                        new
                        {
                            EnrollmentId = 2,
                            EnrollmentDate = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProgramId = 1,
                            Status = "Active",
                            StudentId = 2
                        },
                        new
                        {
                            EnrollmentId = 3,
                            EnrollmentDate = new DateTime(2024, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProgramId = 2,
                            Status = "Active",
                            StudentId = 3
                        },
                        new
                        {
                            EnrollmentId = 4,
                            EnrollmentDate = new DateTime(2023, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProgramId = 2,
                            Status = "Completed",
                            StudentId = 4
                        },
                        new
                        {
                            EnrollmentId = 5,
                            EnrollmentDate = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProgramId = 3,
                            Status = "Deferred",
                            StudentId = 5
                        },
                        new
                        {
                            EnrollmentId = 6,
                            EnrollmentDate = new DateTime(2023, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProgramId = 1,
                            Status = "Active",
                            StudentId = 6
                        },
                        new
                        {
                            EnrollmentId = 7,
                            EnrollmentDate = new DateTime(2024, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProgramId = 2,
                            Status = "Active",
                            StudentId = 7
                        },
                        new
                        {
                            EnrollmentId = 8,
                            EnrollmentDate = new DateTime(2024, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProgramId = 3,
                            Status = "Active",
                            StudentId = 8
                        },
                        new
                        {
                            EnrollmentId = 9,
                            EnrollmentDate = new DateTime(2023, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProgramId = 1,
                            Status = "Completed",
                            StudentId = 9
                        },
                        new
                        {
                            EnrollmentId = 10,
                            EnrollmentDate = new DateTime(2023, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProgramId = 2,
                            Status = "Completed",
                            StudentId = 10
                        },
                        new
                        {
                            EnrollmentId = 11,
                            EnrollmentDate = new DateTime(2023, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProgramId = 3,
                            Status = "Completed",
                            StudentId = 1
                        },
                        new
                        {
                            EnrollmentId = 12,
                            EnrollmentDate = new DateTime(2023, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProgramId = 1,
                            Status = "Active",
                            StudentId = 5
                        });
                });

            modelBuilder.Entity("COMP306402_ProjectDemo.Models.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentId"));

                    b.Property<DateTime>("EnrollmentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StudentId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            StudentId = 1,
                            EnrollmentDate = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "John",
                            LastName = "Doe"
                        },
                        new
                        {
                            StudentId = 2,
                            EnrollmentDate = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Jane",
                            LastName = "Smith"
                        },
                        new
                        {
                            StudentId = 3,
                            EnrollmentDate = new DateTime(2024, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Ali",
                            LastName = "Khan"
                        },
                        new
                        {
                            StudentId = 4,
                            EnrollmentDate = new DateTime(2023, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Maria",
                            LastName = "Garcia"
                        },
                        new
                        {
                            StudentId = 5,
                            EnrollmentDate = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "David",
                            LastName = "Lee"
                        },
                        new
                        {
                            StudentId = 6,
                            EnrollmentDate = new DateTime(2023, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Emily",
                            LastName = "Chen"
                        },
                        new
                        {
                            StudentId = 7,
                            EnrollmentDate = new DateTime(2024, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Mark",
                            LastName = "Wilson"
                        },
                        new
                        {
                            StudentId = 8,
                            EnrollmentDate = new DateTime(2024, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Sarah",
                            LastName = "Brown"
                        },
                        new
                        {
                            StudentId = 9,
                            EnrollmentDate = new DateTime(2023, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Kevin",
                            LastName = "Black"
                        },
                        new
                        {
                            StudentId = 10,
                            EnrollmentDate = new DateTime(2023, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Lisa",
                            LastName = "White"
                        });
                });

            modelBuilder.Entity("COMP306402_ProjectDemo.Models.Enrollment", b =>
                {
                    b.HasOne("COMP306402_ProjectDemo.Models.AcademicProgram", "AcedemicProgram")
                        .WithMany("Enrollments")
                        .HasForeignKey("ProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("COMP306402_ProjectDemo.Models.Student", "Student")
                        .WithMany("Enrollments")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AcedemicProgram");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("COMP306402_ProjectDemo.Models.AcademicProgram", b =>
                {
                    b.Navigation("Enrollments");
                });

            modelBuilder.Entity("COMP306402_ProjectDemo.Models.Student", b =>
                {
                    b.Navigation("Enrollments");
                });
#pragma warning restore 612, 618
        }
    }
}
